language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.11"
after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- mv lib lib-orig
- mv lib-cov lib
- ./node_modules/.bin/mocha test/ -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
- -rf lib
- mv lib-orig lib